### ISSUE TITLE
LLR2 does not function properly for b^n±k

### ISSUE THREAD

**Issue by MathIsFun0** [patnashev/llr2#5]
LLR2 will often crash and report incorrect results when testing candidates of the form b^n±k. It only reports accurate results when running a simple test with `-oGerbicz=0`. As an example, I'll use the probable prime 2^33216-129437.

When running the command `llr2 -d -q"2^33216-129437"`, LLR2 will crash after finishing the test.
After rerunning it with `-oGerbicz=0`, LLR2 reports the incorrect result `2^33216-129437 is not prime.  RES64: 685EFDBECC218E3A.  OLD64: 391CF93C64689DE5` if it resumes from the first test's checkpoint.
If it is ran with `-oGerbicz=0` without the checkpoint, LLR2 reports the correct result `2^33216-129437 is Fermat, Lucas and Frobenius PRP! (P = 5, Q = 3, D = 13)`

The same thing happens when trying to run LLR2 with proofs. When running the command `llr2 -d -oProofName=proof -oProofCount=16 -oProductName=product -oPietrzak=1 -oCachePoints=1 -pSavePoints -q"2^33216-129437"`, LLR2 will give the result `Raw certificate RES64: 68E515788E022EE1` and crash before displaying whether or not the candidate is a probable prime.

LLR2 appears to work more reliably when k is smaller.

**Comment by patnashev** [comment]
3b8d526f4f5021f8b72a889404355c3c25304a99 should resolve the issue.
Do you need binaries?

**Comment by MathIsFun0** [comment]
I don't need binaries, but thanks for offering. With even larger k, LLR2 can still fail. For instance, trying to run a test on 2^33216-509205 will not display whether or not the candidate is prime, thus not completely resolving the issue.

**Comment by MathIsFun0** [comment]
Thank you for the fix. LLR2 works properly now.
